// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.SqlServer;
using System.ComponentModel.DataAnnotations;

namespace Webjet.Backend.Models.Data
{
    // MovieDetails
    public class MovieDetailConfiguration : IEntityTypeConfiguration<MovieDetail>
    {
        public void Configure(EntityTypeBuilder<MovieDetail> builder)
        {
            builder.ToTable("MovieDetails", "dbo");
            builder.HasKey(x => x.MovieId).HasName("PK_MovieDetails").IsClustered();

            builder.Property(x => x.MovieId).HasColumnName(@"MovieId").HasColumnType("nvarchar(20)").IsRequired().HasMaxLength(20).ValueGeneratedNever();
            builder.Property(x => x.Year).HasColumnName(@"Year").HasColumnType("smallint").IsRequired(false);
            builder.Property(x => x.Rated).HasColumnName(@"Rated").HasColumnType("nvarchar(5)").IsRequired(false).HasMaxLength(5);
            builder.Property(x => x.Released).HasColumnName(@"Released").HasColumnType("nvarchar(100)").IsRequired(false).HasMaxLength(100);
            builder.Property(x => x.Runtime).HasColumnName(@"Runtime").HasColumnType("nvarchar(100)").IsRequired(false).HasMaxLength(100);
            builder.Property(x => x.Genre).HasColumnName(@"Genre").HasColumnType("nvarchar(100)").IsRequired(false).HasMaxLength(100);
            builder.Property(x => x.Director).HasColumnName(@"Director").HasColumnType("nvarchar(100)").IsRequired(false).HasMaxLength(100);
            builder.Property(x => x.Writer).HasColumnName(@"Writer").HasColumnType("nvarchar(200)").IsRequired(false).HasMaxLength(200);
            builder.Property(x => x.Actors).HasColumnName(@"Actors").HasColumnType("nvarchar(500)").IsRequired(false).HasMaxLength(500);
            builder.Property(x => x.Plot).HasColumnName(@"Plot").HasColumnType("nvarchar(1000)").IsRequired(false).HasMaxLength(1000);
            builder.Property(x => x.Language).HasColumnName(@"Language").HasColumnType("nvarchar(100)").IsRequired(false).HasMaxLength(100);
            builder.Property(x => x.Country).HasColumnName(@"Country").HasColumnType("nvarchar(100)").IsRequired(false).HasMaxLength(100);
            builder.Property(x => x.Awards).HasColumnName(@"Awards").HasColumnType("nvarchar(100)").IsRequired(false).HasMaxLength(100);
            builder.Property(x => x.Metascore).HasColumnName(@"Metascore").HasColumnType("smallint").IsRequired(false);
            builder.Property(x => x.Rating).HasColumnName(@"Rating").HasColumnType("decimal(3,1)").IsRequired(false);
            builder.Property(x => x.Votes).HasColumnName(@"Votes").HasColumnType("nvarchar(100)").IsRequired(false).HasMaxLength(100);
            builder.Property(x => x.Type).HasColumnName(@"Type").HasColumnType("nvarchar(100)").IsRequired(false).HasMaxLength(100);
            builder.Property(x => x.UpdatedAt).HasColumnName(@"UpdatedAt").HasColumnType("datetimeoffset").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.MovieSummary).WithOne(b => b.MovieDetail).HasForeignKey<MovieDetail>(c => c.MovieId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_MovieDetails_MovieSummaries");
        }
    }

}
// </auto-generated>
