// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.SqlServer;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;

namespace Webjet.Backend.Models.Data
{
    // MovieDetails
    public partial class MovieDetail
    {
        [Key]
        [MaxLength(20)]
        [StringLength(20)]
        [Required(AllowEmptyStrings = true)]
        [Display(Name = "Movie ID")]
        public string MovieId { get; set; } // MovieId (Primary key) (length: 20)

        [Display(Name = "Year")]
        public short? Year { get; set; } // Year

        [MaxLength(5)]
        [StringLength(5)]
        [Display(Name = "Rated")]
        public string Rated { get; set; } // Rated (length: 5)

        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Released")]
        public string Released { get; set; } // Released (length: 100)

        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Runtime")]
        public string Runtime { get; set; } // Runtime (length: 100)

        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Genre")]
        public string Genre { get; set; } // Genre (length: 100)

        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Director")]
        public string Director { get; set; } // Director (length: 100)

        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Writer")]
        public string Writer { get; set; } // Writer (length: 100)

        [MaxLength(500)]
        [StringLength(500)]
        [Display(Name = "Actors")]
        public string Actors { get; set; } // Actors (length: 500)

        [MaxLength(1000)]
        [StringLength(1000)]
        [Display(Name = "Plot")]
        public string Plot { get; set; } // Plot (length: 1000)

        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Language")]
        public string Language { get; set; } // Language (length: 100)

        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Country")]
        public string Country { get; set; } // Country (length: 100)

        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Awards")]
        public string Awards { get; set; } // Awards (length: 100)

        [Display(Name = "Metascore")]
        public short? Metascore { get; set; } // Metascore

        [Display(Name = "Rating")]
        public decimal? Rating { get; set; } // Rating

        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Votes")]
        public string Votes { get; set; } // Votes (length: 100)

        [Required]
        [Display(Name = "Updated at")]
        public DateTimeOffset UpdatedAt { get; set; } // UpdatedAt

        // Foreign keys

        /// <summary>
        /// Parent MovieSummary pointed by [MovieDetails].([MovieId]) (FK_MovieDetails_MovieSummaries)
        /// </summary>
        public MovieSummary MovieSummary { get; set; } // FK_MovieDetails_MovieSummaries

        public MovieDetail()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
