// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.SqlServer;
using System.ComponentModel.DataAnnotations;

namespace Webjet.Backend.Models.Data
{
    // MovieSummaries
    public class MovieSummaryConfiguration : IEntityTypeConfiguration<MovieSummary>
    {
        public void Configure(EntityTypeBuilder<MovieSummary> builder)
        {
            builder.ToTable("MovieSummaries", "dbo");
            builder.HasKey(x => x.MovieId).HasName("PK_MovieSummaries").IsClustered();

            builder.Property(x => x.MovieId).HasColumnName(@"MovieId").HasColumnType("nvarchar(20)").IsRequired().HasMaxLength(20).ValueGeneratedNever();
            builder.Property(x => x.Title).HasColumnName(@"Title").HasColumnType("nvarchar(256)").IsRequired().HasMaxLength(256);
            builder.Property(x => x.Poster).HasColumnName(@"Poster").HasColumnType("nvarchar(2048)").IsRequired().HasMaxLength(2048);
            builder.Property(x => x.Price).HasColumnName(@"Price").HasColumnType("money").IsRequired(false);
            builder.Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType("datetimeoffset").IsRequired();
            builder.Property(x => x.UpdatedAt).HasColumnName(@"UpdatedAt").HasColumnType("datetimeoffset").IsRequired();
        }
    }

}
// </auto-generated>
