// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.SqlServer;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;

namespace Webjet.Backend.Models.Data
{
    // MovieSummaries
    public partial class MovieSummary
    {
        [Key]
        [MaxLength(20)]
        [StringLength(20)]
        [Required(AllowEmptyStrings = true)]
        [Display(Name = "Movie ID")]
        public string MovieId { get; set; } // MovieId (Primary key) (length: 20)

        [MaxLength(256)]
        [StringLength(256)]
        [Required(AllowEmptyStrings = true)]
        [Display(Name = "Title")]
        public string Title { get; set; } // Title (length: 256)

        [MaxLength(2048)]
        [StringLength(2048)]
        [Required(AllowEmptyStrings = true)]
        [Display(Name = "Poster")]
        public string Poster { get; set; } // Poster (length: 2048)

        [Display(Name = "Price")]
        public decimal? Price { get; set; } // Price

        [Required]
        [Display(Name = "Created at")]
        public DateTimeOffset CreatedAt { get; set; } // CreatedAt

        [Required]
        [Display(Name = "Updated at")]
        public DateTimeOffset UpdatedAt { get; set; } // UpdatedAt

        public MovieSummary()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
