// <auto-generated>
// ReSharper disable All

using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.SqlServer;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.SqlTypes;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Webjet.Backend.Models.Data
{
    public class WebjetMoviesDbContext : DbContext, IWebjetMoviesDbContext
    {
        private readonly IConfiguration _configuration;

        public WebjetMoviesDbContext()
        {
        }

        public WebjetMoviesDbContext(DbContextOptions<WebjetMoviesDbContext> options)
            : base(options)
        {
        }

        public WebjetMoviesDbContext(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public DbSet<MovieDetail> MovieDetails { get; set; } // MovieDetails
        public DbSet<MovieSummary> MovieSummaries { get; set; } // MovieSummaries

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured && _configuration != null)
            {
                optionsBuilder.UseSqlServer(_configuration.GetConnectionString(@"DbConnectionString"), builder => { 
                    builder.UseHierarchyId();
                    builder.UseNetTopologySuite();
                });
            }
        }

        public bool IsSqlParameterNull(SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == DBNull.Value);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.ApplyConfiguration(new MovieDetailConfiguration());
            modelBuilder.ApplyConfiguration(new MovieSummaryConfiguration());
        }

    }
}
// </auto-generated>
