// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.EntityFrameworkCore.SqlServer;
using System.ComponentModel.DataAnnotations;

namespace Webjet.Backend.Models.Data
{
    public class WebjetMoviesDbContextFactory : IDesignTimeDbContextFactory<WebjetMoviesDbContext>
    {
        public WebjetMoviesDbContext CreateDbContext(string[] args)
        {
            return new WebjetMoviesDbContext();
        }
    }
}
// </auto-generated>
